name: steppers
description: A Flutter steppers package.
version: 0.0.1
author: zeucxb <zeucxb@gmail.com>
homepage: https://github.com/zeucxb/fultter_steppers
repository: https://github.com/zeucxb/fultter_steppers

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
